<?php
/*helps authenticate a user*/
//error_reporting(0);
class Company extends MY_Controller {

	public $c_companyTypes;
	public $forwardemail;
	public $nicename;

    public function __construct() {
        parent::__construct();
        $this->load->model("companymodel",'c');
		$this->load->model("brandmodel",'b');
        $this->load->model("companytype",'company_type');
        $this->load->model("foodtypes",'foodtypes');
        $this->load->model("usersmodel",'users');
		$this->forwardemail=$this->config->item('email_server');
		$this->nicename=$this->config->item('email_nicename');
		$this->is_logedIn();
    }


    public  function index($filter=""){
       $result= $this->c->get_details();
    }
	public function add($id="")
	{
		$this->is_user_allowed();
		if(isset($_POST))
		{	
			$emailAddress=trim($this->input->get_post('email',TRUE));
		
			$filter=array('userName' => $emailAddress,'userEmail'=>$emailAddress);
			$res=$this->users->get_details($filter);
			$res_count=count($res);
			if($res_count>0 && $emailAddress!=="")
			{
				$data = array('reg_msg'=> "The users email already exist, please try another one");	
				$this->session->set_userdata($data);
				redirect('manageCompanies');
			}
			$contact_person=$this->input->get_post('c_person',TRUE);
			$cmpny=$this->input->get_post('inputCName',TRUE);
            $company_code=$this->input->get_post('inputCcode',TRUE);           
		    $ctype=$this->input->get_post('inputCType',TRUE);
			$foodtype=$this->input->get_post('inputFType',TRUE);			
			$nms=$this->company_type->get_companyName($ctype);
			$ctype_name=$nms[0]->company_type_name;			
			if($foodtype=="0")
			{
				$c_foodtype="N/A";
			}
			else
			{
				$filter=array('vehicleId' => $foodtype);
				$q=$this->foodtypes->get_details($filter);
				$c_foodtype=$q[0]->vehicleName;
			}							
			$phone=$this->input->get_post('phone',TRUE);
			$uname=$ctype."ADM".gencode(4);
			$pass=genBigcode(8);
			
			/*$filter=array('userName' => $emailAddress);
   	  		$available_users=count($this->users->get_details($filter));
			
	  		while($available_users>0)
	  		{
	    		$uname=$ctype."ADM".gencode(4);
				$filter=array('userName' => $uname);
   	    		$cde=count($this->users->get_details($filter));
	  		}*/
			
				
		if(empty($id))
		{	
			$code=genBigcode(6);
	  		$filter=array('activationcode' => $code);
   	  		$cde=count($this->users->get_details($filter));
	  		while($cde>0)
	  		{
	    		$code=genBigcode(6);
				$filter=array('activationcode' => $code);
   	    		$cde=count($this->users->get_details($filter));
	  		}
   	  	$url = site_url()."activate/$code";
		
      	$message="Dear $contact_person,\r\nYou have been created as the administrator for $cmpny.......\r\n\r\nCompany details::\r\n Company Name: $cmpny\r\n  Company Code: $company_code\r\n Company Type: $ctype_name";
		
		if($c_foodtype!=="N/A")
		{
			$message.="\r\n Vehicle Type: $c_foodtype";
		}
		$message.="\r\n\r\nYour Login credentials ::\r\n Username: $emailAddress\r\n  Password: $pass\r\nPlease click on the link bellow to activate your accoutnt:$url.\r\n\r\nThis email was atomaticaly generated by the system";

	     $this->email->set_newline("\r\n");  
         $this->email->from($this->forwardemail,$this->nicename);
         $this->email->subject('Account registration request');
         $this->email->message($message);
         $this->email->to($emailAddress);
     if (!$this->email->send())
      { 
		$data = array('reg_msg'=> "Could not create company account. The email server is not responding. Please try again later or contact admin.");	
	    $this->session->set_userdata($data);
        redirect('manageCompanies');
      }
	  else
	  {
		 
		 $resp=$this->c->add_company($c_foodtype);
			if($resp==TRUE)
			{
				 $filter=array('company_name' => $cmpny,'company_code' => $company_code);				
				 $rsp=$this->c->get_details($filter);
				 $c_id=$rsp[0]->company_id;
				 $affiliation=$rsp[0]->affiliation;
				 $details = array(
                'usersFullnames'=>$contact_person,
                'userName'=>$emailAddress,
                'userEmail' =>$emailAddress,
                'company_id' => $c_id,
				'userPassword'=>md5($pass),
				'userRights'=>1,
				'user_role'=>1,
				'activationcode'=>$code,
				'is_active'=>0
            	);
				//add_company
				$data = array('reg_msg'=> "Company and default user created. Login credentials sent to $emailAddress.");
				$this->users->add_user($details);
	     		$this->session->set_userdata($data);
		 		redirect('manageCompanies');
			}
	  	  }	
        }	
		else
		{	
			$resp=$this->c->update_dets($c_foodtype,$id);
			if($resp==TRUE)
			{
				redirect('manageCompanies');
			}
		}
		
		}
    }
 function change_dets($id)
{
	$this->is_user_allowed();
     $names=trim($this->input->get_post('c_person',TRUE));
   	 $userEmail=trim($this->input->get_post('email',TRUE));
   	 $phone=trim($this->input->get_post('phone',TRUE));
	 $pass=genBigcode(8);
	//die();
	 	$filter=array('company_id' => $id);
	 	$dets=$this->c->get_details($filter);	
		$old_email=trim($dets[0]->emailAddress);
		if($old_email===trim($userEmail))
			{
				$this->c->update_cperson($id);
	    		redirect('manageCompanies');
			}
		else
			{
			$filter=array('userEmail' => $old_email,'company_id' =>$id);
			$dets=$this->users->get_details($filter);
			$uid=trim($dets[0]->usersID);
				$url = base_url();
      			$message="Dear $names,\r\nYou changed your login credentials. The new details are:\r\n Username: $userEmail\r\n  Password: $pass\r\nPlease click on the link bellow to access your account: $url.\r\n\r\nThis email was atomaticaly generated by the system";
			//		echo $message;
			//		die();
	     		$this->email->set_newline("\r\n");  
         		$this->email->from($this->forwardemail,$this->nicename);
         		$this->email->subject('Changed login credentials.');
         		$this->email->message($message);
         		$this->email->to($userEmail);
     			if (!$this->email->send())
      				{ 
						$data = array('updt_msg'=> "Could not update user account details. The email server is not responding. Please try again later or contact admin.");	
	    				$this->session->set_userdata($data);
       					redirect('manageCompanies');
      				}
	  			else
	  				{
						
		 				$this->c->update_cperson($id);
						$details = array('usersFullnames' =>$names,'userName' =>$userEmail,'userEmail' =>$userEmail,'userPassword'=>md5($pass));
						$this->users->activate($uid,$details);
						//print_r($details);
						$data = array('updt_msg'=> "Company default user details updated. Login credentials sent to $userEmail.");
						$this->session->set_userdata($data);
	     				redirect('manageCompanies');
	  			    }
			
	  	}
	
}
    public function update()
	{
	 $this->is_user_allowed();
     $this->c->update();   
    }
	public function update_dets($id)
	{
		 $this->is_user_allowed();
		 $resp=$this->c->update_dets($id);  
		 if($resp==TRUE)
			{
				redirect('openCompany/'.$id);
			}
	}
	
	public function add_form($id="") 
	{
		$this->is_user_allowed();
		$data['item_id']=$id;
		if(!empty($id))
		{
			$result= $this->c->get_details(array('company_id'=>$id));
			$data['result']=$result;			
		}
	    $data['comptypes']=$this->company_type->get_details();
		$data['foodtype']=$this->company_type->get_Typedetails();
		$this -> load -> view('dashboard/companies/add_companies', $data);
	}
	public function edit_cperson($id) 
	{
		$this->is_user_allowed();
		$data['item_id']=$id;
		$result= $this->c->get_details(array('company_id'=>$id));
		$data['result']=$result;
		$this -> load -> view('dashboard/companies/edit_cperson', $data);
	}
	public function edit_user($id="") 
	{
		$this->is_user_allowed();
		$data['item_id']=$id;
		if(!empty($id))
		{
			$result= $this->c->get_details(array('company_id'=>$id));
			$data['result']=$result;			
		}
	    $data['comptypes']=$this->company_type->get_details();
		$data['foodtype']=$this->company_type->get_Typedetails();
		$this -> load -> view('dashboard/companies/edit_cmpany', $data);
	}
	
	private function getCompanyTypes() 
	{
		return $this -> c_companyTypes=$this->company_type->get_details();
	}	
		
	public function manageCompanies()
	{
		$cat = $this -> session -> userdata('vehicle');
		 $data['h_title']="Registered companies";
		 $data['mh_title']="COMPANIES";
		 $headers=array('Company Name','Company Code','Company Type','Contact Person','Email','Actions');
		 	 
		 $data['content_page'] = 'companies/manage_companies';
		 $tmpl = array ( 'table_open'  => '<table id="big_table" border="0" cellpadding="0" cellspacing="0" class="mytable" style="font-size:10px; width:100%">' );
		 $this->table->set_template($tmpl);         
		 $this->table->set_heading($headers); 
		$this -> load -> view('template_loggedin', $data);  	
	}

	function getList()
		{
			if($this->read_rights==="true")
			{
			$this->datatables->select('company_id,company_name,company_code,company_type_name,contact_person,emailAddress')
			->join('company_type','company_type.company_type_id=company.company_type_id')			
			->unset_column('company_id')			
			->add_column('Actions', get_buttons('$1'),'company_id')
			->where('company_name != "MOPHS"')
			->from('company');       
			}
			else
			{
				$this->datatables->select('company_id,company_name,company_code,company_type_name,contact_person,emailAddress')
			->join('company_type','company_type.company_type_id=company.company_type_id')			
			->unset_column('company_id')	
			->add_column('Actions', get_buttons_non_admin('$1'),'company_id')
			->where('company_name != "MOPHS"')
			->from('company');       
			}
			echo $this->datatables->generate();
		}
	public  function openCompany($id="user")
		{
			$o_val=$id;
			if($id==="user" || $id==="settings")
			{
			 $id= $this ->session -> userdata('companyID');
			}
		   $filter=array('company_id'=>$id);
		   $result= $this->c->get_details($filter);
		   $c_name=ucfirst(trim($result[0]->company_name));
		   $data['h_title']="Profile & settings";
		   $data['mh_title']=strtoupper($c_name);
		   
		   $data['content_page'] =($o_val==="settings")? 'companies/companyPage_oversite':'companies/companyPage';
		   
		   $data['result']=$result;
		   $data['company_id']=$id;
		   $data['content']="Vehicles";
		   $tmpl = array ( 'table_open'  => '<table id="big_table" border="0" cellpadding="0" cellspacing="0" class="mytable" style="font-size:10px; width:100%">' );
		 $this->table->set_template($tmpl);    
		 
		  $headers=array('Brand Name');
		 if($this->read_rights==="true")
			{
				array_push($headers,'Actions');
			}
		      
		 $this->table->set_heading($headers); 
		   $this -> load -> view('template_loggedin', $data); 
		}

	function getBrands($id)
		{
		if($this->read_rights==="true")
			{
			$this->datatables->select('brand_id,brand_name','company_name') 
			->unset_column('brand_id')
			->add_column('Actions', get_brandbuttons('$1'),'brand_id') 
			->where('company.company_id', $id)
			->join('company','company.company_id = companybrands.company_id')
			->from('companybrands');
			}
			else
			{
				$this->datatables->select('brand_id,brand_name','company_name') 
			->unset_column('brand_id')
			->where('company.company_id', $id)
			->join('company','company.company_id = companybrands.company_id')
			->from('companybrands');
			}			
			
			echo $this->datatables->generate();
		}	
		
	public function addProduct($id="") 
	{
		$this->is_user_allowed();
	   $filter=array('company_id'=>$this ->session -> userdata('companyID'));
       $result= $this->c->get_details($filter);
	   $data['c_name']=ucfirst(trim($result[0]->company_name));
		if(!empty($id))
		{			
			$result= $this->b->get_details(array('brand_id'=>$id));
			$data['result']=$result;			
		}
		$data['item_id']=$id;
		$this -> load -> view('dashboard/companies/addProduct', $data);		
	}
public function add_prod($id="")
	{
		$this->is_user_allowed();
		if($id=="")
		{
		 	$this->b->add();
			redirect('openCompany/'.$this ->session -> userdata('companyID'));
		}
		else
		{
		 	$this->b->update($id);  
			redirect('openCompany/'.$this ->session -> userdata('companyID'));
		}	
			
	}
public function delProduct($id)
	{
		$this->is_user_allowed();
		 	if($this->b->delete($id)==true)
			{
				echo $this->delete_success_msg;
			}
			else
			{
				echo $this->delete_er_msg;
			}
	}	
		
}
?>